package health.creda.bridge.providers

import ca.uhn.fhir.rest.server.IResourceProvider
import org.hl7.fhir.r4.model.AuditEvent
import org.springframework.stereotype.Component

/**
 * Read-side audit only (§8.2.4): AuditEvent records *who queried which subgraph*, generated by
 * HAPI's standard auditing infrastructure — NOT the identity events themselves (those are
 * CredaProvenance). This provider exposes read/search over those access records.
 *
 * TODO(bridge-verify): wire HAPI's AuditEvent interceptor to capture reads, and back read/search
 * with that store. Stubbed here to keep the M7 scaffold bounded.
 */
@Component
class AuditEventResourceProvider : IResourceProvider {
    override fun getResourceType(): Class<AuditEvent> = AuditEvent::class.java
}
